/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */
package com.github.jjobes.slidedatetimepicker;

public final class R {
	public static final class color {
		public static final int gray_holo_dark = 0x7f070000;
		public static final int gray_holo_light = 0x7f070001;
	}
	public static final class drawable {
		public static final int selection_divider = 0x7f020077;
	}
	public static final class id {
		public static final int buttonHorizontalDivider = 0x7f0c01a4;
		public static final int buttonVerticalDivider = 0x7f0c01a6;
		public static final int cancelButton = 0x7f0c01a5;
		public static final int customTab = 0x7f0c00fa;
		public static final int datePicker = 0x7f0c0101;
		public static final int okButton = 0x7f0c01a7;
		public static final int slidingTabLayout = 0x7f0c01a3;
		public static final int tabText = 0x7f0c00fb;
		public static final int timePicker = 0x7f0c0122;
		public static final int viewPager = 0x7f0c0040;
	}
	public static final class layout {
		public static final int custom_tab = 0x7f03002b;
		public static final int fragment_date = 0x7f03002f;
		public static final int fragment_time = 0x7f030038;
		public static final int slide_date_time_picker = 0x7f03007a;
	}
	public static final class style {
		public static final int AppBaseTheme = 0x7f080000;
		public static final int AppTheme = 0x7f080001;
	}
}
