/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */
package com.github.jjobes.slidedatetimepicker;

public final class R {
	public static final class color {
		public static final int gray_holo_dark = 0x7f070000;
		public static final int gray_holo_light = 0x7f070001;
	}
	public static final class drawable {
		public static final int selection_divider = 0x7f02006a;
	}
	public static final class id {
		public static final int buttonHorizontalDivider = 0x7f0c016a;
		public static final int buttonVerticalDivider = 0x7f0c016c;
		public static final int cancelButton = 0x7f0c016b;
		public static final int customTab = 0x7f0c00c4;
		public static final int datePicker = 0x7f0c00c7;
		public static final int okButton = 0x7f0c016d;
		public static final int slidingTabLayout = 0x7f0c0169;
		public static final int tabText = 0x7f0c00c5;
		public static final int timePicker = 0x7f0c00ef;
		public static final int viewPager = 0x7f0c002a;
	}
	public static final class layout {
		public static final int custom_tab = 0x7f03001f;
		public static final int fragment_date = 0x7f030021;
		public static final int fragment_time = 0x7f03002a;
		public static final int slide_date_time_picker = 0x7f030064;
	}
	public static final class style {
		public static final int AppBaseTheme = 0x7f080000;
		public static final int AppTheme = 0x7f080001;
	}
}
